rvm:
  - 1.8.7
  - 1.9.3
#  - ruby-head
  - jruby
  - rbx-18mode
  - rbx-19mode
services:
  - riak
  - couchdb
  - redis-server
#  - cassandra
  - memcached
  - mongodb
before_install:
  - sudo apt-get install -qq libtokyocabinet8 libtokyocabinet-dev liblzo2-dev
env:
  - "TASK=test:parallel"
  - "TASK=test:non_parallel"
matrix:
  allow_failures:
#    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-18mode
    - rvm: rbx-19mode
  # Parallel tests do not work on jruby
  exclude:
    - rvm: jruby
      env: "TASK=test:parallel"
script: "bundle exec rake $TASK"
